project/config/routes.rb
Rails.application.routes.draw do
  resources :polls
  root to: 'polls#index'

end

project/app/models/poll.rb
class Poll < ActiveRecord::Base

	has_many :vote_options, dependent: :destroy
	validates :topic, presence: true
	accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true
	
end

project/app/models/vote_option.rb
class VoteOption < ActiveRecord::Base
  belongs_to :poll
  validates :title, presence: true
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project/app/controllers/polls_controller.rb
class PollsController < ApplicationController

	def index
		@polls = Poll.all
	end

	def new
		@poll = Poll.new
	end

	def create
		@poll = Poll.new(poll_params)
		if @poll.save
			flash[:sucess] = 'Poll was created'
			redirect_to polls_path
		else
			render 'new'
		end
	end

	def edit
		@poll = Poll.find_by_id(params[:id])
	end

	def update
		@poll = Poll.find_by_id(params[:id])
		if @poll.update_attributes(poll_params)
			flash[:sucess] = 'Poll was updated!'
			redirect_to polls_path
		else
			render 'edit'
		end
	end

	def destroy
		@poll = Poll.find_by_id(params[:id])
		if @poll.destroy
			flash[:sucess] = 'Poll was destroyed!'
		else
			flash[:warning] = 'Error destroying poll...'
		end
		redirect_to polls_path
	end

	private

	def poll_params
		params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :destroy])
	end
	
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/polls_helper.rb
module PollsHelper
end

project/app/views/admin/admin.html.erb
<% content_for(:page_header){"Control panel"} %>

<section class="left_70 white">
	<h2>Your polls</h2>
<% @polls.each do |poll| %>
	<div class="well">
		<h3><%= poll.topic %></h3>

		<div class="btn-group">
			<%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
			<%= link_to 'Delete', poll_path(poll), method: :delete, class: 'btn btn-ganger', data: {confirm: 'Are you sure?'} %>
			<%= link_to 'Open/close', edit_poll_path(poll), class: 'btn btn-default' %>
			<%= link_to 'Stats', poll_path(poll), method: :delete, class: 'btn btn-ganger', data: {confirm: 'Are you sure?'} %>
		</div>
	</div>
<% end %>
</section>
<section class="right_30 white">
	<h2>New poll</h2>
	<p><%= link_to 'Multiple choice', class: 'btn btn-default' %></p>
	<p><%= link_to 'Relate columns', class: 'btn btn-default' %></p>
	<p><%= link_to 'Complete words', class: 'btn btn-default' %></p>
</section>
<div class="clear"></div>

project/app/views/admin/login.html.erb
<section class="flex-center">
	<div class="well">
		<h2>Login</h2>

		<form name="login">
			University e-mail:<br/>
			<input type="text" name="email"/>
			Password:<br/>
			<input type="password" name="password"/>
			<input type="submit" value="Log in"/>
		</form>
	</div>
</section>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EPoll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="/assets/dom.jsPlumb-1.7.6-min.js "></script>
  <script src="/assets/jquery.ui.touch-punch.min.js"></script>
</head>
<body>
	<header class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<a href="/"><img src="assets/surrey.png"/><img src="assets/logo.png"/></a>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to 'Add poll', new_poll_path %></li>
				<li><%= link_to 'Log out', new_poll_path %></li>
			</ul>
		</div>
	</header>

	<section id="content">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<% value %>
			</div>
			<% end %>

			<div class="page-header">
				<h1><%= yield :page_header %></h1>
			</div>
			<%= yield %>
	</section>

</body>
</html>

project/app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
	<%= render 'shared/errors', object: @poll %>

	<div class="form-group">
		<%= f.label :topic %>
		<%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">Options</div>
		<div class="panel-body">
			<%= f.fields_for :vote_options do |options_form| %>
				<%= render 'vote_option_fields', f: options_form %>
			<% end %> 

			<div class="links">
				<%= link_to_add_association 'add option', f, :vote_options %>
			</div>
		</div>
	</div>


	<%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
<% end %>

project/app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control', required: true %>
	</div>
	<%= link_to_remove_association "remove options", f %>
</div>

project/app/views/polls/edit.html.erb
<% content_for(:page_header) {"Edit Poll"} %>
<%= render 'form' %>

project/app/views/polls/index.html.erb
<section class="left_25 white">
	<h2 class="margin_10">New poll</h2>
	<img src="assets/iconSingle.png"/>
	<img src="assets/iconMultiple.png"/>
	<img src="assets/iconRelate.png"/>
	<hr/>
	<h2 class="margin_10">Your polls</h2>
<% @polls.each do |poll| %>
	<div class="well">
		<h3><%= poll.topic %></h3>

		<div class="btn-group">
			<%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
			<%= link_to 'Delete', poll_path(poll), method: :delete, class: 'btn btn-ganger', data: {confirm: 'Are you sure?'} %>
			<%= link_to 'Open/close', edit_poll_path(poll), class: 'btn btn-default' %>
			<%= link_to 'Stats', poll_path(poll), method: :delete, class: 'btn btn-ganger', data: {confirm: 'Are you sure?'} %>
		</div>
	</div>
<% end %>
</section>
<section id="board" class="right_75">
	<article class="question ui-widget-header" id="question1">
		<header>
			pergunta 1
			<nav class="navbar-nav">
				<a href="/"><img src="assets/iconOpen.png"/></a>
				<a href="/"><img src="assets/iconStats.png"/></a>
				<a href="/"><img src="assets/iconEdit.png"/></a>
				<a href="/"><img src="assets/iconBin.png"/></a>
			</nav>
		</header>
		<p>asdjfaçdslkjfsalkjsçlkfjsaklçdjslkjçlksfjsa</p>
		<ul>
			<li id="q1o1">opcoes</li>
			<li id="q1o2">opcoes</li>
			<li id="q1o3">opcoes</li>
		</ul>
	</article>

	<article class="question ui-widget-header" id="question2">
		<header>
			pergunta 2
			<nav class="navbar-nav">
				<a href="/"><img src="assets/iconOpen.png"/></a>
				<a href="/"><img src="assets/iconStats.png"/></a>
				<a href="/"><img src="assets/iconEdit.png"/></a>
				<a href="/"><img src="assets/iconBin.png"/></a>
			</nav>
		</header>
		<p>asdjfaçdslkjfsalkjsçlkfjsaklçdjslkjçlksfjsa</p>
		<ul>
			<li id="q2o1">opcoes</li>
			<li id="q2o2">opcoes</li>
			<li id="q2o3">opcoes</li>
		</ul>
	</article>
</section>

<script>
window.setZoom = function(zoom, instance, transformOrigin, el) {
  transformOrigin = transformOrigin || [ 0.5, 0.5 ];
  instance = instance || jsPlumb;
  el = el || instance.getContainer();
  var p = [ "webkit", "moz", "ms", "o" ],
      s = "scale(" + zoom + ")",
      oString = (transformOrigin[0] * 100) + "% " + (transformOrigin[1] * 100) + "%";

  for (var i = 0; i < p.length; i++) {
    el.style[p[i] + "Transform"] = s;
    el.style[p[i] + "TransformOrigin"] = oString;
  }

  el.style["transform"] = s;
  el.style["transformOrigin"] = oString;

  instance.setZoom(zoom);    
};
	$(function() {
		$(".question").draggable();
		jsPlumb.draggable($(".question"), {
  			containment:$("#board")
		});
		$( "#board" ).droppable();
	});
  	jsPlumb.ready(function() {
  		jsPlumb.setContainer($("#board"));
    	jsPlumb.importDefaults({
  			Connector : [ "Bezier", { curviness: 150 } ],
  			DragOptions : { cursor: "crosshair" },
  			Anchors : [ "Right", "Left" ],
			PaintStyle:{ 
			    lineWidth:2, 
			    strokeStyle:"#567567", 
			    outlineWidth:0
			},
			Endpoint:[ "Dot", { radius:3 } ],
			EndpointStyle : { fillStyle: "#567567"  },
			Anchor : [ 0.5, 0.5, 1, 1 ]
		});

    	var common = {
  			deleteEndpointsOnDetach: false
		};
    	var connections = [{ source:$("#q1o1"), target:$("#q2o3")}];
    	jsPlumb.batch(function() {
  			for (var i = 0, j = connections.length; i < j; i++) {
      			jsPlumb.connect(connections[i], common);
  			}
		});
	});
  </script>

project/app/views/polls/login.html.erb
<% content_for(:page_header){"Use our polls system right now"} %>

<section class="well left_50">
	<h2>Create your account</h2>

	<form name="newUser">
		<label for="name">Name:</label><br/>
		<input type="text" name="name" id="name" /><br/>
		<label for="email">University e-mail:</label><br/>
		<input type="text" name="email" id="email"/><br/>
		<label for="password">Password:</label><br/>
		<input type="password" name="password" id="password" /><br/>
		<label for="confirm">Confirm your password:</label><br/>
		<input type="password" name="confirmPassword" id="confirm" /><br/><br/>
		<input type="submit" value="Create"/>
	</form>

</section>

<section class="well right_50">
	<h2>Login</h2>

	<form name="login">
		<label for="email_login">University e-mail:</label><br/>
		<input type="text" name="email" id="email_login" /><br/>
		<label for="password_login">Password:</label><br/>
		<input type="password" name="password" id="password_login" /><br/><br/>
		<input type="submit" value="Log in"/>
	</form>

</section>
<div class="clear"></div>

project/app/views/polls/new.html.erb
<% content_for(:page_header) {"Create a new poll"} %>
<%= render 'form' %>

project/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div class="alert alert-warning">
		<h4>The following errors were found:</h4>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>